cp

diff --git a/.buildkite/images/docker/Dockerfile b/.buildkite/images/docker/Dockerfile
--- a/.buildkite/images/docker/Dockerfile
+++ b/.buildkite/images/docker/Dockerfile
@@ -7,8 +7,9 @@
 #
 ####################################################################################################
 ARG PYTHON_VERSION
+ARG DEBIAN_BASE
 
-FROM python:"${PYTHON_VERSION}-stretch" AS dagster-base-build-image
+FROM python:"${PYTHON_VERSION}-${DEBIAN_BASE}" AS dagster-base-build-image
 LABEL maintainer="Elementl"
 
 # Never prompts the user for choices on installation/configuration of packages
@@ -38,12 +39,12 @@ ENV KIND_VERSION=v0.5.1
 # add a simple script that can auto-detect the appropriate JAVA_HOME value
 # based on whether the JDK or only the JRE is installed
 RUN { \
-		echo '#!/bin/sh'; \
-		echo 'set -e'; \
-		echo; \
-		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
-	} > /usr/local/bin/docker-java-home \
-	&& chmod +x /usr/local/bin/docker-java-home \
+    echo '#!/bin/sh'; \
+    echo 'set -e'; \
+    echo; \
+    echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
+    } > /usr/local/bin/docker-java-home \
+    && chmod +x /usr/local/bin/docker-java-home \
     # do some fancy footwork to create a JAVA_HOME that's cross-architecture-safe
     && ln -svT "/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)" /docker-java-home
 
@@ -51,35 +52,35 @@ RUN set -ex \
     && curl -sL https://deb.nodesource.com/setup_11.x | bash - \
     && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
     && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
-# Deal with slim variants not having man page directories (which causes "update-alternatives"
+    # Deal with slim variants not having man page directories (which causes "update-alternatives"
     && mkdir -p /usr/share/man/man1 \
-# Refresh apt
+    # Refresh apt
     && apt-get update -yqq \
     && apt-get upgrade -yqq \
-# Install deps
+    # Install deps
     && apt-get install -yqq --no-install-recommends \
-        bzip2 \
-        cron \
-        openjdk-8-jre-headless="$JAVA_DEBIAN_VERSION" \
-        openjdk-8-jdk-headless="$JAVA_DEBIAN_VERSION" \
-        nodejs \
-        rsync \
-        software-properties-common \
-        unzip \
-        xz-utils \
-        yarn \
-# Clean up after install process
+    bzip2 \
+    cron \
+    openjdk-8-jre-headless="$JAVA_DEBIAN_VERSION" \
+    openjdk-8-jdk-headless="$JAVA_DEBIAN_VERSION" \
+    nodejs \
+    rsync \
+    software-properties-common \
+    unzip \
+    xz-utils \
+    yarn \
+    # Clean up after install process
     && apt-get autoremove -yqq --purge \
     && apt-get clean \
     && rm -rf \
-        /var/lib/apt/lists/* \
-        /tmp/* \
-        /var/tmp/* \
-        /usr/share/doc \
-        /usr/share/doc-base \
-# update-alternatives so that future installs of other OpenJDK versions don't change /usr/bin/java
+    /var/lib/apt/lists/* \
+    /tmp/* \
+    /var/tmp/* \
+    /usr/share/doc \
+    /usr/share/doc-base \
+    # update-alternatives so that future installs of other OpenJDK versions don't change /usr/bin/java
     && update-alternatives --get-selections | awk -v home="$(readlink -f "$JAVA_HOME")" 'index($3, home) == 1 { $2 = "manual"; print | "update-alternatives --set-selections" }' \
-# Validate installation
+    # Validate installation
     && [ "$(readlink -f "$JAVA_HOME")" = "$(docker-java-home)" ] \
     && update-alternatives --query java | grep -q 'Status: manual' \
     && java -version
@@ -130,24 +131,24 @@ RUN curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-c
     && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
     && apt-get -yqq update \
     && apt-get -yqq install \
-        apt-transport-https \
-        ca-certificates \
-        curl \
-        docker-ce \
-        gnupg2 \
-        libpq-dev\
-        pandoc \
-        sbt \
-# Clean up after install process
+    apt-transport-https \
+    ca-certificates \
+    curl \
+    docker-ce \
+    gnupg2 \
+    libpq-dev\
+    pandoc \
+    sbt \
+    # Clean up after install process
     && apt-get autoremove -yqq --purge \
     && apt-get clean \
     && rm -rf \
-        /var/lib/apt/lists/* \
-        /tmp/* \
-        /var/tmp/* \
-        /usr/share/doc \
-        /usr/share/doc-base \
-# Validate
+    /var/lib/apt/lists/* \
+    /tmp/* \
+    /var/tmp/* \
+    /usr/share/doc \
+    /usr/share/doc-base \
+    # Validate
     && sbt sbtVersion
 
 # Install kubectl and kind CLI utils
